# $NetBSD: options.mk,v 1.7 2016/06/19 17:04:44 Chips Exp $

DISTNAME=	wine-1.9.14
CATEGORIES=	wip
MASTER_SITES=	http://mirrors.ibiblio.org/wine/source/1.9/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	Chips@NetBSD.org
HOMEPAGE=	https://www.winehq.org/
COMMENT=	A compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, Mac OSX, & BSD.
LICENSE=	gnu-lgpl-v2.1

USE_LANGUAGES=		c c++
EXTRACT_USING=		gtar
GNU_CONFIGURE=		yes

.include "options.mk"

.include "../../mk/bsd.pkg.mk"
